using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;

namespace ResumeBuilder.Data;

/// <summary>
/// Creates the schema and brings databases created by older versions up to date.
/// The project has no EF migrations history, so upgrades are applied as idempotent steps:
/// missing tables are created from the current model, and missing columns are added.
/// </summary>
public static class DatabaseInitializer
{
    private const string EmptyGuid = "00000000-0000-0000-0000-000000000000";

    /// <summary>SQLite has no uuid() function; this builds a v4 guid per row from randomblob().</summary>
    private const string RandomGuidSql =
        "lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || " +
        "'-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))";

    /// <summary>
    /// The columns <see cref="AddedColumns"/> will add to an existing install, per table. Read by
    /// the schema test so that a property added to a model without an entry here fails a test
    /// instead of failing on a user's machine.
    /// </summary>
    public static IReadOnlyDictionary<string, IReadOnlyList<string>> ColumnsAddedSinceFirstRelease =>
        AddedColumns.ToDictionary(t => t.Key, t => (IReadOnlyList<string>)t.Value.Select(c => c.Column).ToList());

    /// <summary>Columns added after the first release, per table.</summary>
    private static readonly Dictionary<string, (string Column, string Ddl)[]> AddedColumns = new()
    {
        ["Resumes"] = new[]
        {
            ("RowVersion", $"TEXT NOT NULL DEFAULT '{EmptyGuid}'"),
            ("SyncId", $"TEXT NOT NULL DEFAULT '{EmptyGuid}'"),
            ("BaseResumeId", "INTEGER NULL"),
            ("TargetRole", "TEXT NOT NULL DEFAULT ''"),
            ("JobDescription", "TEXT NOT NULL DEFAULT ''")
        }
    };

    /// <summary>
    /// Brings the schema up to date and reports what happened on the way, so the app can tell the
    /// user when the pre-upgrade backup failed instead of upgrading a file nobody has a copy of.
    /// </summary>
    /// <exception cref="DatabaseOpenException">
    /// The file is not a database SQLite can open. Thrown as a typed error with the path in it,
    /// because the alternative is an unhandled SqliteException at startup with no window to show it.
    /// </exception>
    public static DatabaseInitializationReport Initialize(ResumeDbContext context)
    {
        var path = DatabaseBackup.PathOf(context);

        try
        {
            context.Database.EnsureCreated();

            // Back up before touching the schema, not on every launch. Upgrades are the only moment
            // this code rewrites a file the user cannot reproduce from memory, and the steps below are
            // hand-written rather than generated by a migration - so a mistake surfaces on someone
            // else's machine. Backing up unconditionally would copy the database every start for no
            // benefit; backing up here makes exactly the risky moment recoverable.
            var backupNeeded = HasPendingSchemaChanges(context);
            var backup = backupNeeded ? DatabaseBackup.Create(context) : BackupResult.Skipped;

            CreateMissingTables(context);
            AddMissingColumns(context);
            BackfillSyncIds(context);

            return new DatabaseInitializationReport(path, backupNeeded, backup.Path, backup.Error);
        }
        catch (Microsoft.Data.Sqlite.SqliteException ex)
        {
            throw new DatabaseOpenException(path, ex);
        }
    }

    /// <summary>
    /// Whether <see cref="CreateMissingTables"/> or <see cref="AddMissingColumns"/> would do
    /// anything. Read-only, and deliberately cheap enough to run on every start.
    /// </summary>
    private static bool HasPendingSchemaChanges(ResumeDbContext context)
    {
        try
        {
            var existingTables = ExistingTables(context);

            foreach (var statement in SplitStatements(context.Database.GenerateCreateScript()))
            {
                var table = TableBeingCreated(statement);
                if (table != null && !existingTables.Contains(table))
                {
                    return true;
                }
            }

            foreach (var (table, columns) in AddedColumns)
            {
                var existingColumns = ExistingColumns(context, table);
                if (existingColumns.Count == 0)
                {
                    continue;
                }

                if (columns.Any(c => !existingColumns.Contains(c.Column)))
                {
                    return true;
                }
            }

            return false;
        }
        catch (Exception)
        {
            // If the check itself fails, treat it as "something is off" and take the backup -
            // the copy is cheap and this is precisely when one is worth having.
            return true;
        }
    }

    /// <summary>
    /// EnsureCreated is a no-op once the file exists, so a table added in a later version would
    /// never appear on an existing install. Create those from the model's own DDL.
    /// </summary>
    private static void CreateMissingTables(ResumeDbContext context)
    {
        var existing = ExistingTables(context);
        var script = context.Database.GenerateCreateScript();

        foreach (var statement in SplitStatements(script))
        {
            var table = TableBeingCreated(statement);
            if (table == null || existing.Contains(table))
            {
                continue;
            }

            context.Database.ExecuteSqlRaw(statement);
            existing.Add(table);
        }

        // Indexes for the tables we just created come as separate statements.
        foreach (var statement in SplitStatements(script))
        {
            var indexed = TableBeingIndexed(statement);
            if (indexed == null || !existing.Contains(indexed))
            {
                continue;
            }

            try
            {
                context.Database.ExecuteSqlRaw(statement);
            }
            catch (Microsoft.Data.Sqlite.SqliteException)
            {
                // Index already exists - nothing to do.
            }
        }
    }

    private static void AddMissingColumns(ResumeDbContext context)
    {
        foreach (var (table, columns) in AddedColumns)
        {
            var existing = ExistingColumns(context, table);
            if (existing.Count == 0)
            {
                continue;
            }

            foreach (var (column, ddl) in columns)
            {
                if (existing.Contains(column))
                {
                    continue;
                }

                // Table/column/type all come from the AddedColumns literal above, and SQL cannot
                // parameterize identifiers or DDL types anyway - there is no caller input here.
#pragma warning disable EF1002 // Risk of vulnerability to SQL injection.
                context.Database.ExecuteSqlRaw($"ALTER TABLE \"{table}\" ADD COLUMN \"{column}\" {ddl}");
#pragma warning restore EF1002
            }
        }
    }

    /// <summary>Gives resumes saved before sync existed a stable identity, once.</summary>
    private static void BackfillSyncIds(ResumeDbContext context)
    {
        // Every fragment here is a compile-time constant - no caller input reaches this SQL.
        const string sql =
            "UPDATE \"Resumes\" SET \"SyncId\" = " + RandomGuidSql +
            " WHERE \"SyncId\" = '" + EmptyGuid + "' OR \"SyncId\" IS NULL";

        context.Database.ExecuteSqlRaw(sql);
    }

    private static IEnumerable<string> SplitStatements(string script) =>
        script.Split(';', StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .Where(s => s.Length > 0);

    private static string? TableBeingCreated(string statement)
    {
        var match = Regex.Match(statement, @"^CREATE\s+TABLE\s+""(?<name>[^""]+)""", RegexOptions.IgnoreCase);
        return match.Success ? match.Groups["name"].Value : null;
    }

    private static string? TableBeingIndexed(string statement)
    {
        var match = Regex.Match(
            statement,
            @"^CREATE\s+(UNIQUE\s+)?INDEX\s+""[^""]+""\s+ON\s+""(?<table>[^""]+)""",
            RegexOptions.IgnoreCase);
        return match.Success ? match.Groups["table"].Value : null;
    }

    private static HashSet<string> ExistingTables(ResumeDbContext context)
    {
        var tables = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        Query(context, "SELECT name FROM sqlite_master WHERE type = 'table'", reader => tables.Add(reader.GetString(0)));
        return tables;
    }

    private static HashSet<string> ExistingColumns(ResumeDbContext context, string table)
    {
        var columns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        Query(context, $"PRAGMA table_info(\"{table}\")", reader => columns.Add(reader.GetString(1)));
        return columns;
    }

    private static void Query(ResumeDbContext context, string sql, Action<System.Data.Common.DbDataReader> onRow)
    {
        var connection = context.Database.GetDbConnection();
        var shouldClose = connection.State != System.Data.ConnectionState.Open;
        if (shouldClose)
        {
            connection.Open();
        }

        try
        {
            using var command = connection.CreateCommand();
            command.CommandText = sql;
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                onRow(reader);
            }
        }
        finally
        {
            if (shouldClose)
            {
                connection.Close();
            }
        }
    }
}

/// <summary>What <see cref="DatabaseInitializer.Initialize"/> found and did.</summary>
/// <param name="DatabasePath">The file, or null for an in-memory database.</param>
/// <param name="BackupNeeded">Whether the schema was about to change, which is the only time a backup is taken.</param>
/// <param name="BackupPath">Where the copy landed, when one was made.</param>
/// <param name="BackupError">Why the copy failed, when it did. The upgrade still went ahead.</param>
public sealed record DatabaseInitializationReport(string? DatabasePath, bool BackupNeeded, string? BackupPath, string? BackupError)
{
    /// <summary>A backup was needed and could not be made: the one case the user must hear about.</summary>
    public bool BackupFailed => BackupNeeded && BackupError is not null;
}

/// <summary>
/// The database file exists but SQLite cannot open it: corrupt, truncated, or not a database at
/// all. Carries the path so the message can say which file, and where the backups next to it are.
/// </summary>
public sealed class DatabaseOpenException : Exception
{
    public string? DatabasePath { get; }

    public DatabaseOpenException(string? path, Exception inner)
        : base(path is null
            ? "The database could not be opened: " + inner.Message
            : $"The database at {path} could not be opened: {inner.Message}", inner)
    {
        DatabasePath = path;
    }

    /// <summary>Backups next to the database, newest first; empty when there is no path or none exist.</summary>
    public IReadOnlyList<string> AvailableBackups =>
        DatabasePath is null ? Array.Empty<string>() : DatabaseBackup.List(System.IO.Path.GetDirectoryName(DatabasePath)!);
}
