<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResumeBuilder.Core\ResumeBuilder.Core\ResumeBuilder.Core.csproj" />
    <ProjectReference Include="..\ResumeBuilder.Export\ResumeBuilder.Export\ResumeBuilder.Export.csproj" />
    <ProjectReference Include="..\ResumeBuilder.Data\ResumeBuilder.Data\ResumeBuilder.Data.csproj" />
    <ProjectReference Include="..\ResumeBuilder.Templates\ResumeBuilder.Templates\ResumeBuilder.Templates.csproj" />
  </ItemGroup>

</Project>
