<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ResumeBuilder.Core\ResumeBuilder.Core\ResumeBuilder.Core.csproj" />
    <ProjectReference Include="..\..\ResumeBuilder.Templates\ResumeBuilder.Templates\ResumeBuilder.Templates.csproj" />
  </ItemGroup>

</Project>
